### ISSUE TITLE
Empty state for videos and pages

### ISSUE THREAD

**Issue by mykhailodanilenko** [OwnTube-tv/web-client#156]
Blocks of videos and pages need to have an "empty" state to indicate that there is no error but the data list is empty (length === 0)

**Comment by mkl-adsn** [comment]
If possible, I believe empty categories and playlist sections should be hidden altogether as they otherwise just clutter the site.  For the other cases I think a plain text message similar to the error messages will suffice as empty channels and view histories in most cases should be a temporary problem.

Figma: https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=908-11802&t=KYlUj6pngVhB0APk-1

**Comment by mkl-adsn** [comment]
Empty version of collection pages:

Channels page
History page
Playlists page
Categories page

**Comment by mkl-adsn** [comment]
Added empty states
Channels: https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=925-18580&t=Y7ZXHPhd2Uo6hYzQ-1
Categories: https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=925-18926&t=Y7ZXHPhd2Uo6hYzQ-1
History: https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=925-17898&t=Y7ZXHPhd2Uo6hYzQ-1
